name: 'Validate FIX Design'
description: |
  Permite validar si un cambio es de tipo FIX. Si es un FIX, no necesita pasar por Gobierno de APIs y se genera automaticamente un TAG para que pueda ser usado en la ejecucion del Pipeline Jenkins para el despliegue de la API al AZ APIM en ambiente Desarrollo.
runs:
  using: "composite"
  steps:
    - name: Descargar repositorio git
      id: checkout_repository
      uses: actions/checkout@v4

    - name: Validar ultimo mensaje commit
      shell: bash
      id: validate_last_msg_commit
      run: |
        last_msg_commit=`git log --format=%B -n 1 HEAD | head -n 1`
        echo $last_msg_commit
        if [[ $last_msg_commit == '${{ vars.LAST_MSG_COMMIT }}' ]]; then
          result="TRUE"
        else
          result="FALSE"
        fi
        echo "is_valid=$result" >> $GITHUB_OUTPUT