name: Update Main Version
run-name: Move ${{ github.event.inputs.major_version }} to ${{ github.event.inputs.target }}

on:
  workflow_dispatch:
    inputs:
      tag_target:
        type: choice
        description: El tag a actualizar
        options:
          - v1
          - v2

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Git config
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
    - name: Update tag
      run: git tag -fa -m "Actualizando TAG ${{ github.event.inputs.tag_target }}" ${{ github.event.inputs.tag_target }}
    - name: Push new tag
      run: git push origin ${{ github.event.inputs.tag_target }} --force